sso:
  store:
    type: mock
  cache:
    type: redis

spring:
  profiles:
    active: dev

### freemarker
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request

  session:
    store-type: redis

### resources
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/

